from docx import Document
from docx.shared import Pt
from pathlib import Path


class DocxGenerator:

    @staticmethod
    def generate(document_title: str, sections: dict) -> str:

        doc = Document()

        title = doc.add_heading(document_title, level=1)
        title.runs[0].font.size = Pt(20)

        doc.add_paragraph(
            "Generated by Autonomous AI Agent using Ollama\n"
        )

        doc.add_page_break()

        for heading, content in sections.items():

            h = doc.add_heading(heading, level=2)
            h.runs[0].font.size = Pt(16)

            p = doc.add_paragraph()
            p.style.font.size = Pt(11)
            p.add_run(content)

        output_dir = Path("output")
        output_dir.mkdir(exist_ok=True)

        filename = document_title.replace(" ", "_") + ".docx"

        filepath = output_dir / filename

        doc.save(filepath)

        return str(filepath)